### ISSUE TITLE
Known Issue: Truncated strings on EN side of "Thank you screen" strings in Manage survey languages on Firefox

### ISSUE THREAD

**Issue by IsmaelInRedlands** [zhif7782/0525-holistic-testing#27] opened 2023-06-08 15:20 UTC
#### Test case URL
- https://github.com/ArcGIS/survey123-test-functional/issues/243

-----------

#### Device OS and version
Windows 10 x64 - Chrome 114.0.5735.110

#### Device make and model
 - 

#### Survey123 app and version
Website: 3.18.26
- 

-----------

#### Steps to reproduce
1. Load https://survey123beta.arcgis.com and sign in
2. Create new survey and add some questions
3. Click Options - Manage survey languages

#### Actual result
Truncated strings on EN side of "Thank you screen" strings in Manage survey languages on Firefox

#### Expected result
Strings should be fully visible

-----------

#### Bug severity
High

-----------

#### Additional notes
Not reproducible on Live 3.17 version - regression. Reproducible only on Firefox; Chrome, Edge and Safari are fine.

![a8d296a3-7705-484b-9444-52d80737bd70](https://github.com/zhif7782/0525-holistic-testing/assets/5918689/ca3c9a55-d4b0-44ee-811b-595b0278dc65)
![f19f3ef8-d03e-4508-993b-54f853abefd7](https://github.com/zhif7782/0525-holistic-testing/assets/5918689/4100f5e8-56b9-4bac-a5eb-d5cc08cbe061)

**Comment by IsmaelInRedlands** [comment] 2023-06-08 15:21
To be fixed in RC3.
https://devtopia.esri.com/Beijing-R-D-Center/survey123-hub/issues/6548

**Comment by fendiaoxiaoshuazi** [comment] 2023-06-09 10:16
The issue is fixed in RC3, close the issue.

**Closed as completed by fendiaoxiaoshuazi** 2023-06-09 10:16 UTC
Labels: bug
